console.time("The Code took");
console.log("Hello World");
console.error("Error Found");
console.log("Error Found");
console.warn("This is warning");
console.log("Warning");
console.log(3+ 4);
console.log(8 + 7);
console.log(true);
console.log([1, 45, 6, 78]);
console.log({ name: "Zano", marks: 22 });
console.table({ name: "Zano", marks: 22 });
//console.clear();
console.log("Hello");
console.timeEnd ("The Code took");
console.assert (120 > 450, "Wrong age");
console.log("Last line");
console.log(10 > 15);
console.log(15 > 10);